# fly.toml app configuration file generated for business-contract-analyzer-server on 2024-10-28T01:18:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'business-contract-analyzer-server'
primary_region = 'lax'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
